<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a350a0b68656c6c6f2e70726f746f12087475746f7269616c22140a0548656c6c6f120b0a0377686f180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

