<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace Tutorial;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tutorial.Hello</code>
 */
class Hello extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string who = 1;</code>
     */
    protected $who = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $who
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Hello::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string who = 1;</code>
     * @return string
     */
    public function getWho()
    {
        return $this->who;
    }

    /**
     * Generated from protobuf field <code>string who = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWho($var)
    {
        GPBUtil::checkString($var, True);
        $this->who = $var;

        return $this;
    }

}

